# Generated by Django 5.1 on 2024-08-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_foodphotos_gallery_description_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.AddField(
            model_name='food',
            name='category_name',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main Dishes', 'Main Dishes'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks')], default='Main Dishes', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
