# Generated by Django 5.1 on 2024-09-03 11:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='food',
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message="Telefon raqamingizni to'g'ri kiriting. Masalan: +998901234567 yoki 901234567.", regex='^\\+?998?\\d{9,13}$')]),
        ),
        migrations.AlterField(
            model_name='foodphotos',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodphotos', to='restaurant.food'),
        ),
    ]
